### ISSUE TITLE
TypeLoadError

### ISSUE THREAD

**Issue by Foxite** [Foxite/Discord.Net#1]
This issue is created on behalf of @nminchow who contacted me via email. I have now enabled issues on this repo.

He received the following error:
```
Exception has occurred: CLR/System.TypeLoadException


An unhandled exception of type 'System.TypeLoadException' occurred in System.Private.CoreLib.dll: 'Method 'get_Flags' in type 'Discord.WebSocket.SocketUserMessage' from assembly 'Discord.Net.WebSocket, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'
   at Discord.WebSocket.BaseSocketClient..ctor(DiscordSocketConfig config, DiscordRestApiClient client)
   at Discord.WebSocket.DiscordShardedClient..ctor(Int32[] ids, DiscordSocketConfig config, DiscordSocketApiClient client)
   at Discord.WebSocket.DiscordShardedClient..ctor(DiscordSocketConfig config)
```

Without looking, I can already tell that this has to do with dotnet using the wrong dll, which can be traced back to me not bothering to change the name of the assembly when uploading it to nuget. That has previously caused me a lot of trouble, so I'm going to upload the myget package under a different name. Hang tight.

**Comment by Foxite** [comment]
I've uploaded the packages to myget. They're now called Discord.NetFoxite.* to stop dotnet from thinking they're interchangable. They also have to `-foxite` version suffix, just to make it a bit more clear that I guess.

[Rest](https://www.myget.org/feed/foxite/package/nuget/Discord.NetFoxite.Rest)  
[Core](https://www.myget.org/feed/foxite/package/nuget/Discord.NetFoxite.Core)  
[WebSocket](https://www.myget.org/feed/foxite/package/nuget/Discord.NetFoxite.WebSocket)

It's likely you only need these three, and since WebSocket depends on the other two, you can just reference that one. I've also done the other packages for completeness.

[Commands](https://www.myget.org/feed/foxite/package/nuget/Discord.NetFoxite.Commands)  
[WS4Net](https://www.myget.org/feed/foxite/package/nuget/Discord.NetFoxite.Providers.WS4Net)  
[Webhook](https://www.myget.org/feed/foxite/package/nuget/Discord.NetFoxite.Webhook)

**Comment by nminchow** [comment]
Thanks for the quick fix on this. Worked like a charm!
